CREATE TABLE Person
  PERMAID int(11) NOT NULL,
  DAYID int(11) NOT NULL,
  USECROSSWALK smallint(6) DEFAULT 0,
  USEROAD smallint(6) DEFAULT 0,
  NS smallint(6) DEFAULT NULL,
  EW smallint(6) DEFAULT NULL,
  PRIMARY KEY (PERMAID)
);

CREATE TABLE Frame (
  DATE datetime NOT NULL,
  PATH char(128) NOT NULL,
  FRAMEID int(11) NOT NULL,
  PRIMARY KEY (DATE)
);

CREATE TABLE Coordinate(
   TOTAL    INTEGER NOT NULL AUTO_INCREMENT,
   PERMAID  INTEGER   NOT NULL,
   DATE     DATETIME NOT NULL,
   XCOORD   INTEGER   DEFAULT 0,
   YCOORD   INTEGER   DEFAULT 0,
   PRIMARY KEY (TOTAL),
   FOREIGN KEY (DATE) REFERENCES Frame (DATE),
   FOREIGN KEY (PERMAID) REFERENCES Person (PERMAID)
);

CREATE TABLE Contains(
   PERMAID  INT          NOT NULL,
   DATE    DATETIME      NOT NULL,
   PRIMARY KEY (PERMAID, DATE),
   FOREIGN KEY (PERMAID) REFERENCES Person (PERMAID),
   FOREIGN KEY (DATE) REFERENCES Frame (DATE)
);
